---
- name: Create advanced resource {{ resource.key }}
  xml:
    path: "{{ xml_path }}"
    xpath: "/cib/configuration/resources/{{ resource.value.type }}[@id='{{ resource.key }}']"
  check_mode: false

- name: Configure attributes for {{ resource.key }}
  include_tasks: _nvpair.yml
  vars:
    nvpair_parent: >-
      {{ '/cib/configuration/resources/' ~
      '%(type)s[@id="%(id)s"]/meta_attributes[@id="%(id)s-meta_attributes"]'
      | format(type = resource.value.type, id = resource.key) }}
    parent_id: "{{ resource.key }}"
  with_dict: "{{ resource.value.meta | default({}) }}"
  loop_control:
    loop_var: nvpair
    label: "{{ '{' ~ nvpair.key ~ ': ' ~ nvpair.value ~ '}' }}"
  when: resource.value.type != 'group'

- name: Create resources in {{ resource.key }}
  include_tasks: _primitive-old.yml
  vars:
    primitive_parent: >-
      {{ '/cib/configuration/resources/%(type)s[@id="%(id)s"]'
      | format(type = resource.value.type, id = resource.key) }}
    parent_id: "{{ resource.key }}"
  with_dict: "{{ resource.value.resources | default({}) }}"
  loop_control:
    loop_var: primitive
