---
- name: Create resource group {{ group.key }}
  xml:
    path: "{{ xml_path }}"
    xpath: "/cib/configuration/resources/group[@id='{{ group.key }}']"
  check_mode: false

- name: Create resources in {{ group.key }}
  include_tasks: _group-element.yml
  vars:
    primitive_parent: /cib/configuration/resources/group[@id='{{ group.key }}']
    parent_id: "{{ group.key }}"
  loop: "{{ group.value | default([]) }}"
  loop_control:
    loop_var: element
