---
- name: Create {{ constraint.type }} constraint
  xml:
    path: "{{ xml_path }}"
    xpath: |-
      {{  "/cib/configuration/constraints/rsc_" ~ constraint.type ~ "[@id='id_" }}
      {%- if constraint.type == 'location' %}
      {{    ['rsc', 'node'] | map('extract', constraint) | list | to_json | hash('sha1') }}
      {%- elif constraint.type == 'colocation' %}
      {{    ['rsc', 'with-rsc'] | map('extract', constraint) | list | to_json | hash('sha1') }}
      {%- else %}
      {{    ['first', 'then'] | map('extract', constraint) | list | to_json | hash('sha1') }}
      {%- endif -%}
      {{  "']" }}
