---
- name: Install Pacemaker Configuration System package
  package:
    name: pcs
    state: installed

- name: Enable and start PCS daemon
  service:
    name: pcsd
    enabled: true
    state: started

- name: Ensure the password for the cluster user
  user:
    name: "{{ pacemaker_user }}"
    system: true
    password: "{{ pacemaker_password | password_hash('sha512', ansible_hostname) }}"

- name: Authenticate all nodes
  command: >
    pcs cluster auth
    {{ pacemaker_hosts | default(ansible_play_batch) | join(' ') }}
    -u {{ pacemaker_user }} -p {{ pacemaker_password }}
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup cluster message bus
  run_once: true
  command: >
    pcs cluster setup --name {{ pacemaker_cluster_name }}
    {{ pacemaker_hosts | default(ansible_play_batch) | join(' ') }}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start all cluster nodes
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - corosync
    - pacemaker

- name: Query cluster properties
  run_once: true
  command: crm_attribute --quiet --query --name={{ item.key | replace('_', '-') }}
  with_dict: "{{ pacemaker_properties }}"
  when: pacemaker_properties is defined
  register: crm_attr
  changed_when: false

- name: Set cluster properties
  run_once: true
  command: pcs property set {{ item.key | replace('_', '-') }}={{ item.value }}
  with_items: "{{ crm_attr.results | default([]) }}"
  loop_control:
    loop_var: result
  when: pacemaker_properties[result.item.key] != result.item.value

- name: Set cluster resources
  run_once: true
  include_tasks: resource.yml
  with_items: "{{ pacemaker_resources }}"
  when: pacemaker_resources is defined
