---
- name: Install PCS package
  package:
    name: pcs
    state: installed

- name: Enable and start PCS daemon
  service:
    name: pcsd
    enabled: true
    state: started

- name: Set password for the user {{ pacemaker_user }}
  user:
    name: "{{ pacemaker_user }}"
    system: true
    password: "{{ pacemaker_password | password_hash('sha512', ansible_hostname) }}"

- name: Authenticate all nodes
  command: >
    pcs cluster auth
    {{ pacemaker_hosts | default(ansible_play_batch) | join(' ') }}
    -u {{ pacemaker_user }} -p {{ pacemaker_password }}
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup message bus
  run_once: true
  command: >
    pcs cluster setup --name {{ pacemaker_cluster_name }}
    {{ pacemaker_hosts | default(ansible_play_batch) | join(' ') }}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start all nodes
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - corosync
    - pacemaker

- name: Create a temporary file
  tempfile:
    suffix: .xml
  register: pacemaker_config
  run_once: true
  check_mode: false
  changed_when: false

- name: Dump cluster configuration
  shell: cibadmin --query > {{ pacemaker_config.path | quote }}
  run_once: true
  check_mode: false
  changed_when: false
