---
- name: Create multi-state resource {{ adv_resource.key }}
  xml:
    path: "{{ xml_path }}"
    xpath: "/cib/configuration/resources/master[@id='{{ adv_resource.key }}']"

- name: Configure attributes for {{ adv_resource.key }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: "/cib/configuration/resources/master[@id='{{ adv_resource.key }}']/meta_attributes"
  with_dict: "{{ adv_resource.value.meta | default({}) }}"
  loop_control:
    loop_var: nvpair
    label: "{{ '{' ~ nvpair.key ~ ': ' ~ nvpair.value ~ '}' }}"

- name: Create resources in {{ adv_resource.key }}
  include_tasks: primitive.yml
  vars:
    primitive_parent: "/cib/configuration/resources/master[@id='{{ adv_resource.key }}']"
  with_dict: "{{ adv_resource.value.resources | default({}) }}"
  loop_control:
    loop_var: primitive
