---
- name: |-
    {{  'Set ' ~ nvpair.key ~ ': ' }}
    {%- if nvpair.value is sameas(true) %}
    {{    'true' }}
    {%- elif nvpair.value is sameas(false) %}
    {{    'false' }}
    {%- else %}
    {{    nvpair.value }}
    {%- endif %}
  xml:
    path: "{{ xml_path }}"
    xpath: >-
      {{ nvpair_parent ~
      ('/nvpair[@name="%s" and @id="%s-%s"]' | format(nvpair.key, parent_id, nvpair.key)) }}
    attribute: value
    value: |-
      {%  if nvpair.value is sameas(true) %}
      {{    'true' }}
      {%- elif nvpair.value is sameas(false) %}
      {{    'false' }}
      {%- else %}
      {{    nvpair.value }}
      {%- endif %}
