---
- name: Set value for {{ name }}
  xml:
    path: "{{ path }}"
    xpath: '{{ parent }}/nvpair[@name="{{ name }}"]'
    attribute: value
    value: |-
      {%  if value is sameas(true) %}
      {{    'true' }}
      {%- elif value is sameas(false) %}
      {{    'false' }}
      {%- else %}
      {{    value }}
      {%- endif %}
