---
- name: Set value for {{ nvpair_name }}
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ nvpair_parent }}/nvpair[@name="{{ nvpair_name }}"]'
    attribute: value
    value: |-
      {%  if nvpair_value is sameas(true) %}
      {{    'true' }}
      {%- elif nvpair_value is sameas(false) %}
      {{    'false' }}
      {%- else %}
      {{    nvpair_value }}
      {%- endif %}
