---
- name: Set value for {{ prop_name }}
  xml:
    path: "{{ xml_file }}"
    xpath: '{{ prop_parent }}/nvpair[@name="{{ prop_name }}"]'
    attribute: value
    value: |-
      {%  if prop_value is sameas(true) %}
      {{    'true' }}
      {%- elif prop_value is sameas(false) %}
      {{    'false' }}
      {%- else %}
      {{    prop_value }}
      {%- endif %}

- name: Set ID for {{ prop_name }}
  xml:
    path: "{{ xml_file }}"
    xpath: '{{ prop_parent }}/nvpair[@name="{{ prop_name }}"]'
    attribute: id
    value: "{{ prop_id_prefix }}-{{ prop_name }}"
