---
- name: >-
    Create operation {{ op_properties.name | mandatory }}
    interval {{ op_properties.interval | mandatory }}
  xml:
    path: "{{ xml_path }}"
    xpath: >-
      {{ op_parent ~ ('/op[@id="%s-%s-interval-%s"]'
      | format(parent_id, op_properties.name, op_properties.interval)) }}

- name: >-
    Set properties for {{ op_properties.name }}
    interval {{ op_properties.interval | mandatory }}
  xml:
    path: "{{ xml_path }}"
    xpath: >-
      {{ op_parent ~ ('/op[@id="%s-%s-interval-%s"]'
      | format(parent_id, op_properties.name, op_properties.interval)) }}
    attribute: "{{ property.key }}"
    value: |-
      {%  if property.value is sameas(true) %}
      {{    'true' }}
      {%- elif property.value is sameas(false) %}
      {{    'false' }}
      {%- else %}
      {{    property.value }}
      {%- endif %}
  with_dict: "{{ op_properties }}"
  loop_control:
    loop_var: property
    label: "{{ '{' ~ property.key ~ ': ' ~ property.value ~ '}' }}"
