---
- name: Create primitive {{ primitive_id }}
  xml:
    path: "{{ primitive_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]'

- name: Set type for {{ primitive_id }}
  xml:
    path: "{{ primitive_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]'
    attribute: "{{ together.0 }}"
    value: "{{ together.1 }}"
  with_together:
    - ['class', 'provider', 'type']
    - "{{ primitive_type.split(':') }}"
  loop_control:
    loop_var: together

- name: Configure attributes for {{ primitive_id }}
  include_tasks: nvpair.yml
  vars:
    nvpair_path: default.xml
    nvpair_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]/instance_attributes'
    nvpair_name: "{{ attribute.key }}"
    nvpair_value: "{{ attribute.value }}"
  with_dict: "{{ primitive_options }}"
  loop_control:
    loop_var: attribute

- name: Configure meta attributes for {{ primitive_id }}
  include_tasks: nvpair.yml
  vars:
    nvpair_path: default.xml
    nvpair_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]/meta_attributes'
    nvpair_name: "{{ attribute.key }}"
    nvpair_value: "{{ attribute.value }}"
  with_dict: "{{ primitive_meta }}"
  loop_control:
    loop_var: attribute
