---
- name: Create primitive {{ primitive_id }}
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]'

- name: Set type for {{ primitive_id }}
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]'
    attribute: "{{ together.0 }}"
    value: "{{ together.1 }}"
  with_together:
    - ['class', 'provider', 'type']
    - "{{ primitive_type.split(':') }}"
  loop_control:
    loop_var: together

- name: Configure attributes for {{ primitive_id }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]/instance_attributes'
  with_dict: "{{ primitive_options }}"
  loop_control:
    loop_var: nvpair

- name: Configure meta attributes for {{ primitive_id }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]/meta_attributes'
  with_dict: "{{ primitive_meta }}"
  loop_control:
    loop_var: nvpair

- name: Configure operations for {{ primitive_id }}
  include_tasks: op.yml
  vars:
    op_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive_id }}"]/operations'
  loop: "{{ primitive_op }}"
  loop_control:
    loop_var: op_properties
