---
- name: Create primitive {{ primitive.key }}
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]'
  notify: Push cluster configuration

- name: Set type for {{ primitive.key }}
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]'
    attribute: "{{ together.0 }}"
    value: "{{ together.1 }}"
  with_together:
    - ['class', 'provider', 'type']
    - "{{ primitive.value.type.split(':') }}"
  loop_control:
    loop_var: together
  notify: Push cluster configuration

- name: Configure attributes for {{ primitive.key }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]/instance_attributes'
  with_dict: "{{ primitive.value.options | default({}) }}"
  loop_control:
    loop_var: nvpair
  notify: Push cluster configuration

- name: Configure meta attributes for {{ primitive.key }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]/meta_attributes'
  with_dict: "{{ primitive.value.meta | default({}) }}"
  loop_control:
    loop_var: nvpair
  notify: Push cluster configuration

- name: Configure operations for {{ primitive.key }}
  include_tasks: op.yml
  vars:
    op_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]/operations'
  loop: "{{ primitive.value.op | default([]) }}"
  loop_control:
    loop_var: op_properties
  notify: Push cluster configuration
